version: '3'

services:

  redis-server:
    image: 'redis:latest'
    ports:
      - 6379:6379
  
  mongo-server:
    image: 'mongo:latest'
    ports:
      - 27017:27017

  mongo-server-test:
    image: 'mongo:latest'
        
  node-app-test: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - REDIS_HOST=redis://redis-server
      - REDIS_PORT=6379
      - MONGO_HOST=mongodb://mongo-server-test
      - MONGO_PORT=27017
      - SERVER_PORT=8080
      - CACHE_DURATION=2
    command: ['npm', 'run', 'test']

  node-app: 
    depends_on: 
      - node-app-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - REDIS_HOST=redis://redis-server
      - REDIS_PORT=6379
      - MONGO_HOST=mongodb://mongo-server
      - MONGO_PORT=27017
      - SERVER_PORT=8080
      - CACHE_DURATION=2