name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REDIS_HOST: redis://localhost/
      REDIS_PORT: 6379
      MONGO_HOST: mongodb://localhost:27017
      SERVER_PORT: 8080
      CACHE_DURATION: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: shogo82148/actions-setup-redis@v1
      - uses: supercharge/mongodb-github-action@1.3.0
      - run: npm install && npm run test
